limits_config:
  allow_structured_metadata: true
  reject_old_samples: true
  reject_old_samples_max_age: 168h

storage_config:
  tsdb_shipper:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /tmp/loki/tsdb-cache
  #     index_gateway_client:
  #       # only applicable if using microservices where index-gateways are independently deployed.
  #       # This example is using kubernetes-style naming.
  #       server_address: dns:///index-gateway.<namespace>.svc.cluster.local:9095
  filesystem:
    directory: /var/loki/chunks

schema_config:
  configs:
  - from: 2024-07-14
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 30m
  max_chunk_age: 2h
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /var/loki/wal/

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

compactor:
  working_directory: /var/loki/compactor
